# Generated by Django 4.0.5 on 2022-06-11 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_projects_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='link',
            field=models.URLField(blank=True, db_index=True, max_length=128, unique=True),
        ),
    ]
