# Generated by Django 4.0.5 on 2022-06-11 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0007_category_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='category',
        ),
    ]
