# Generated by Django 4.0.5 on 2022-06-11 04:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0008_remove_projects_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='database.category'),
        ),
    ]
