# Generated by Django 4.0.5 on 2022-06-11 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0009_projects_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='githublink',
            field=models.URLField(blank=True, db_index=True, max_length=128, unique=True),
        ),
    ]
