# Generated by Django 4.0.5 on 2022-06-11 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0011_alter_projects_githublink_alter_projects_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='githublink',
            field=models.URLField(blank=True, max_length=128),
        ),
    ]
