# Generated by Django 4.0.5 on 2022-06-11 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0012_alter_projects_githublink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='githublink',
            field=models.URLField(blank=True, db_index=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='projects',
            name='link',
            field=models.URLField(blank=True, db_index=True, max_length=128, unique=True),
        ),
    ]
