# Generated by Django 4.0.5 on 2022-06-11 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0014_alter_projects_githublink'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='githublink',
        ),
        migrations.AddField(
            model_name='projects',
            name='github_link',
            field=models.URLField(blank=True),
        ),
    ]
