# Generated by Django 4.0.5 on 2022-06-11 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0015_remove_projects_githublink_projects_github_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='github_link',
        ),
    ]
