# Generated by Django 4.0.5 on 2022-06-11 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0016_remove_projects_github_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='link',
            field=models.URLField(blank=True, max_length=128),
        ),
    ]
