# Generated by Django 4.0.5 on 2022-06-11 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0017_alter_projects_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='link',
        ),
    ]
