# Generated by Django 4.0.5 on 2022-06-11 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0018_remove_projects_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='githublink',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projects',
            name='link',
            field=models.URLField(default=2),
            preserve_default=False,
        ),
    ]
