# Generated by Django 4.0.5 on 2022-06-16 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0020_alter_projects_githublink_alter_projects_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('from_where', models.CharField(max_length=50)),
                ('massage', models.TextField(blank=True, null=True)),
                ('project_comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='database.projects')),
            ],
        ),
    ]
